version: '3.1'
volumes:
    grafana_data: {}
    dashboards: {}
    database: {}

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - TERM=linux
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./database:/tmp/database
