{
 "title": "Expense Reporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Account",
    "query": "select distinct account from expense_report "
   },
   {
    "name": "from",
    "label": "From Date",
    "query": "2026-01-01,2025-01-01,2024-01-01,2023-01-01"
   },
   {
    "name": "to",
    "label": "To Date",
    "query": "2026-12-31,2025-12-31,2024-12-31,2023-12-31"
   },
   {
    "name": "category",
    "label": "category",
    "query": "SELECT distinct category FROM expense_report "
   },
   {
    "name": "subcategory",
    "query": "SELECT distinct subcategory FROM expense_report where category = '$category'"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Yearly Expense",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    SUM(amount) AS total_amount\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n",
     "rawQueryText": "SELECT \n    SUM(amount) AS total_amount\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  \n    SUM(amount) AS total_amount\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and category = '$category'",
     "rawQueryText": "SELECT  \n    SUM(amount) AS total_amount\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and category = '$category'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Expense Monthly",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT \n    SUM(amount) AS total_amount, \n    strftime('%Y-%m', expensed_date) AS monthly\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\nGROUP BY \n     monthly\nORDER BY \n    monthly, category;\n",
     "rawQueryText": "SELECT \n    SUM(amount) AS total_amount, \n    strftime('%Y-%m', expensed_date) AS monthly\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\nGROUP BY \n     monthly\nORDER BY \n    monthly, category;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Expense by Category",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT \n    SUM(amount) AS total_amount, \n    category\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\nGROUP BY \n     category\nORDER BY \n     total_amount desc;\n     ",
     "rawQueryText": "SELECT \n    SUM(amount) AS total_amount, \n    category\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\nGROUP BY \n     category\nORDER BY \n     total_amount desc;\n     ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Expense Monthly Category",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT  \n    SUM(amount) AS total_amount, \n    strftime('%Y-%m', expensed_date) AS month\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and category = '$category'\nGROUP BY \n      month\nORDER BY \n    month\n",
     "rawQueryText": "SELECT  \n    SUM(amount) AS total_amount, \n    strftime('%Y-%m', expensed_date) AS month\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and category = '$category'\nGROUP BY \n      month\nORDER BY \n    month\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Expense Monthly SubCategory",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT  \n    SUM(amount) AS total_amount, \n    strftime('%Y-%m', expensed_date) AS month\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and subcategory = '$subcategory' and category = '$category'\nGROUP BY \n      month\nORDER BY \n    month\n",
     "rawQueryText": "SELECT  \n    SUM(amount) AS total_amount, \n    strftime('%Y-%m', expensed_date) AS month\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and subcategory = '$subcategory' and category = '$category'\nGROUP BY \n      month\nORDER BY \n    month\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Expense by SubCategory",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT  \n    SUM(amount) AS total_amount, \n    subcategory\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and category = '$category'\nGROUP BY \n      subcategory\nORDER BY \n    total_amount desc",
     "rawQueryText": "SELECT  \n    SUM(amount) AS total_amount, \n    subcategory\nFROM \n    expense_report \nWHERE \n    account = '$account' \n    AND expensed_date BETWEEN '$from' AND '$to'\n    and category = '$category'\nGROUP BY \n      subcategory\nORDER BY \n    total_amount desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}